export const GET_ALL = "GET_ALL";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_LAST_FEW = "GET_LAST_FEW";
export const GET_COUNTRIES_STREAMING = "GET_COUNTRIES_STREAMING";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
